version: '3.3'

services:
   db:
     build: ./db
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     
     ports:
       - 3308:3308
    
     environment:
       MYSQL_DATABASE: star
       MYSQL_ROOT_PASSWORD: 1234
       MYSQL_USER: shri
       MYSQL_PASSWORD: 1234
       DATABASE_HOST: db
       
       

   server:
     build: ./server/star-api-server
     depends_on: 
     - db
     environment:
      MYSQL_DATABASE: star
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: shri
      MYSQL_PASSWORD: 1234
      DATABASE_HOST: db
     ports:
       - "8080:8080"
      
        
     restart: always
 
     
  
       
volumes:
    db_data: {}